"""
Helper file to store all error codes in one place so it is easier to keep track and
add new error codes
"""

ERR_INVALID_REQUEST: str = "error:invalid_request"
ERR_INVALID_SESSION_NAME: str = "error:invalid_session_name"
ERR_INVALID_PLAYER_NAME: str = "error:invalid_player_name"
ERR_INVALID_MAX_PLAYERS: str = "error:invalid_max_players"
ERR_INVALID_SESSION_PASSWORD: str = "error:invalid_session_password"
ERR_SESSION_ALREADY_CREATED_FOR_ADDRESS: str = "error:session_already_created_for_address"
ERR_SESSION_EXISTS: str = "error:session_exists"
ERR_SESSION_NON_EXISTENT: str = "error:session_non_existent"
ERR_SESSION_PASSWORD_MISMATCH: str = "error:password_mismatch"
ERR_SESSION_SINGLE_PLAYER: str = "error:only_one_player_in_session"
ERR_SESSION_FULL: str = "error:session_full"
ERR_SESSION_PLAYER_NAME_IN_USE: str = "error:player_name_in_use"
ERR_SESSION_PLAYER_NON_EXISTENT: str = "error:non_existent_player"
ERR_SESSION_PLAYER_NON_HOST: str = "error:non_host_player"
ERR_SESSION_PLAYER_KICKED_BY_HOST: str = "error:kicked_by_host"
ERR_SESSION_PLAYER_EXIT: str = "error:player_exited_session"
ERR_SESSION_NOT_STARTED: str = "error:session_not_started"
ERR_SESSION_TIMEOUT: str = "error:session_timeout"
ERR_PLAYER_ADDRESS_EXIT_MISMATCH: str = "error:player_address_exit_mismatch"
ERR_PLAYER_TIMEOUT: str = "error:player_timeout"
ERR_PLAYER_ADDRESS_MISMATCH: str = "error:player_address_mismatch"
